### ISSUE TITLE
Input channels and range of values

### ISSUE THREAD

**Issue by ferjad** [prlz77/vgg-face.pytorch#2]
Thank you for the port.

I see that you are using opencv to read the test image. Since opencv output tensor is BGR and not RGB, I am wondering if the original network was trained with this sequence of channels?

Moreover, Is there a reason that the input is not normalized by 255 or is that a carry forward from the original model?

**Comment by prlz77** [comment]
Hey, sorry for the delay.

As you already suspect, I just followed the same transformation as in the original model trained by the VGG group for compatibility reasons.

**Comment by ferjad** [comment]
> Hey, sorry for the delay.
> 
> As you already suspect, I just followed the same transformation as in the original model trained by the VGG group for compatibility reasons.

Thank you for your reply. Can you please confirm that the network is trained with BGR color channels as used in your test script?

**Comment by prlz77** [comment]
Yes, it was originaly trained with BGR and that's why I use cv2.

**Comment by ferjad** [comment]
> Yes, it was originaly trained with BGR and that's why I use cv2.

Great! Closing the issue.
