### ISSUE TITLE
What is the input image format?

### ISSUE THREAD

**Issue by Podidiving** [prlz77/vgg-face.pytorch#8]
Hi :wave:

I was wondering: what is the correct input image format? According to your code the correct format is `BGR`; [here](https://github.com/vlfeat/matconvnet/blob/1e5ae7b70fc1074bf8a2a5617e698e54072fbb2c/examples/vggfaces/cnn_vgg_faces.m#L23C6-L23C12) `imread` function is used; though I'm not sure it also returns `BGR` format. Moreover, an example in the repo works both with `BGR` and `RGB` formats. Can you help me understand which image format is correct one?

**Comment by prlz77** [comment]
Hi,

It is in BGR, see https://github.com/prlz77/vgg-face.pytorch/issues/2#issuecomment-557896581, https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_gui/py_image_display/py_image_display.html
